<?php
/**
 * @var FlashMessage $flash
 * @var Locale $locale
 * @var Device $device
 *
 * @var int $code
 */
use Simplon\Core\Views\FlashMessage;
use Simplon\Device\Device;
use Simplon\Locale\Locale;

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <title>Error page</title>
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="/assets/app.min.css">
</head>
<body style="background:#fff">

    <div style="text-align: center">
        <h1>Error #<?= $code ?></h1>
    </div>

</body>
</html>