<?php
/**
 * @var Locale $locale
 * @var FlashMessage $flash
 * @var Device $device
 */

use Simplon\Core\Views\FlashMessage;
use Simplon\Device\Device;
use Simplon\Locale\Locale;

?>
<div class="ui grid">
    <div class="sixteen wide column">
        <?= $locale->get('items-label') ?>
    </div>
    <div class="sixteen wide column">
        <strong><?= $locale->get('format-date-label') ?></strong>&nbsp;<?= $locale->get('format-date') ?>&nbsp;(<?= $locale->getCurrentLocale() ?>)
    </div>
</div>